# Question 4:
## Use any of the methods we have learned so far (eg. kNN, PCA, DT, and their variants or combinations, and/or chapter 5 methods), to produce a better overall prediction accuracy and runtime on the Forest Cover Type data (from UCI ML repo), than the example in the lecture notes. Explain why and how your method is better.

In [ ]:
# import drive 
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
### INSERT YOUR PATH to data HERE: ###
my_path = '/content/drive/My Drive/covtype.data'
train = pd.read_csv(my_path,header=None)

In [ ]:
train.iloc[:,54]=train.iloc[:,54].astype('category')
pd.DataFrame(train.iloc[:,0:54])

0    1   2    3    4     5    6    7   ...  46  47  48  49  50  51  52  53
0       2596   51   3  258    0   510  221  232  ...   0   0   0   0   0   0   0   0
1       2590   56   2  212   -6   390  220  235  ...   0   0   0   0   0   0   0   0
2       2804  139   9  268   65  3180  234  238  ...   0   0   0   0   0   0   0   0
3       2785  155  18  242  118  3090  238  238  ...   0   0   0   0   0   0   0   0
4       2595   45   2  153   -1   391  220  234  ...   0   0   0   0   0   0   0   0
...      ...  ...  ..  ...  ...   ...  ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..
581007  2396  153  20   85   17   108  240  237  ...   0   0   0   0   0   0   0   0
581008  2391  152  19   67   12    95  240  237  ...   0   0   0   0   0   0   0   0
581009  2386  159  17   60    7    90  236  241  ...   0   0   0   0   0   0   0   0
581010  2384  170  15   60    5    90  230  245  ...   0   0   0   0   0   0   0   0
581011  2383  165  13   60    4    67  231  244  ...   0   0   0   0   0   0   0   0

[581012 rows x 54 columns]

# Comparison: The original prediction for reference

In [ ]:
from sklearn import tree
import time
start_time = time.time()
clf = tree.DecisionTreeClassifier(max_depth=6)

clf = clf.fit(train.iloc[:,0:54], pd.DataFrame(train.iloc[:,54]))
y_pred = clf.predict(train.iloc[:,0:54])
end_time = time.time()

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(pd.DataFrame(train.iloc[:,54]), pd.DataFrame(y_pred))
print("Confusion Matrix")
print(cm)
print("Total correct predictions:")
print(158304+212829+31382+869+567+601+1119)
print("Total time using PCA with 4 components and K = 20")
print(round((end_time - start_time), 4), "seconds")

       54
0       5
1       5
2       2
3       2
4       5
...    ..
581007  3
581008  3
581009  3
581010  3
581011  3

[581012 rows x 1 columns]
        0
0       2
1       2
2       2
3       2
4       2
...    ..
581007  3
581008  3
581009  3
581010  3
581011  3

[581012 rows x 1 columns]
Confusion Matrix
[[158304  49858     90      0     53      5   3530]
 [ 65797 212829   3880      6    419     62    308]
 [     0   4002  31382    263      7    100      0]
 [     0     20   1858    869      0      0      0]
 [    93   8511    322      0    567      0      0]
 [     0   4618  12060     88      0    601      0]
 [  8931    380      0      0      0      0  11199]]
Total correct predictions:
405671
Total time using PCA with 4 components and K = 20
3.7855 seconds


#PCA:

First, I wanted to examenine which and how many of the components were important in generating the forest coverage prediction.  I ran explained_variance_ratio_ on all components to determine how much of the variance was explained by each component.  I found that over 99% of the variance could be explained with the first 4 components.  

In [ ]:
from sklearn.decomposition import PCA
X = train.iloc[:,0:54]
Y = pd.DataFrame(train.iloc[:,54])
pca = PCA(n_components=54)
pca.fit(X)
X_pca = pca.transform(X)

In [ ]:
print("Explained variance ratio for each component:")
print(pca.explained_variance_ratio_)
print("Explained variance ratio for the first four components combined:")
print(0.66245284 + 0.30733696 + 0.01771567 + 0.00859396)

Explained variance ratio for each component:
[6.62452842e-01 3.07336958e-01 1.77156711e-02 8.59396354e-03
 3.06776869e-03 4.73187563e-04 2.47005207e-04 1.03769937e-04
 8.01069072e-06 5.27226907e-07 8.98849321e-08 3.02480948e-08
 2.01976449e-08 1.97305536e-08 1.72831812e-08 1.41389395e-08
 1.16160760e-08 1.09253979e-08 1.00106816e-08 8.96595783e-09
 7.62816381e-09 6.97786487e-09 5.97252896e-09 5.69106876e-09
 4.90846804e-09 4.55333622e-09 4.12659020e-09 3.44285401e-09
 3.13819366e-09 2.47725065e-09 2.01324566e-09 1.74829704e-09
 1.57187860e-09 1.31313159e-09 1.17538271e-09 1.02912736e-09
 9.37473264e-10 7.85587604e-10 7.01234538e-10 6.38861046e-10
 5.34413509e-10 4.59027494e-10 4.21196631e-10 3.75535629e-10
 3.34176712e-10 2.38672101e-10 1.87303789e-10 1.20007463e-10
 7.27096970e-11 4.84920352e-11 4.24543885e-11 1.22351890e-12
 5.50766367e-33 5.50766367e-33]
Explained variance ratio for the first four components combined:
0.99609943


I tried various values of K and found that 20 was the best most often.  This is the confusion matrix, the number correct, and the time it takes to run this method.

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
import time
start_time = time.time()
knn = KNeighborsRegressor(n_neighbors=20)
knn.fit(X_pca, Y)
pca = PCA(n_components=4)
pca.fit(X)
X_pca = pca.transform(X)
knn.fit(X_pca, Y)
y_pred = knn.predict(X_pca).round()
end_time = time.time()

In [ ]:
from sklearn.metrics import confusion_matrix
print("Confusion matrix:")
print(confusion_matrix(pd.DataFrame(train.iloc[:,54]), pd.DataFrame(y_pred)))
print("Total correct predictions:")
print(184924+261753+26378+1810+2814+5587+1336)
print("Total time using PCA with 4 components and K = 20:")
print(round((end_time - start_time), 4), "seconds")

Confusion matrix:
[[184924  22870   2906    961    155     24      0]
 [  8190 261752  11094   2178     86      1      0]
 [     0   1577  26378   6774   1022      3      0]
 [     0      0    520   1810    390     27      0]
 [     0    215   2547   3915   2814      2      0]
 [     0      7    571   4521   6681   5587      0]
 [     0    151    768   1800   1927   2498  13366]]
Total correct predictions:
484602
Total time using PCA with 4 components and K = 20:
20.2837 seconds


# Random Forest with and without parallel 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import time


X_train, X_test, y_train, y_test = train_test_split(train.iloc[:,0:54], pd.DataFrame(train.iloc[:,54]), test_size=1000)
start_time = time.time()
clf = RandomForestRegressor()
clf = clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)
end_time = time.time()

from sklearn.metrics import confusion_matrix
print("Confusion matrix (Random Forest):")
print(confusion_matrix(pd.DataFrame(y_test), pd.DataFrame(y_pred.round())))
print("Total time(Random Forest):")
print(round((end_time - start_time), 4), "seconds")


start_time = time.time()
clf = RandomForestRegressor(n_jobs=-1)
clf = clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)
end_time = time.time()
print("Confusion matrix (Random Forest Parallel):")
print(confusion_matrix(pd.DataFrame(y_test), pd.DataFrame(y_pred.round())))
print("Total time(Random Forest Parallel):")
print(round((end_time - start_time), 4), "seconds")

Confusion matrix (Random Forest):
[[344  16   3   2   0   1   0]
 [  3 484   4   0   0   0   0]
 [  0   0  60   1   0   1   0]
 [  0   0   0   5   1   0   0]
 [  0   0   2   2  11   0   0]
 [  0   0   2   1   3  22   0]
 [  0   0   1   2   0   3  26]]
Total time(Random Forest):
822.8674 seconds
Confusion matrix (Random Forest Parallel):
[[342  18   3   2   1   0   0]
 [  4 481   6   0   0   0   0]
 [  0   0  59   2   0   1   0]
 [  0   0   0   5   1   0   0]
 [  0   0   2   3  10   0   0]
 [  0   0   2   1   4  21   0]
 [  0   0   2   1   0   4  25]]
Total time(Random Forest Parallel):
619.7996 seconds


# Adaboost:

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
import time 

X_train, X_test, y_train, y_test = train_test_split(train.iloc[:,0:54], pd.DataFrame(train.iloc[:,54]), test_size=1000)

start_time = time.time()
clf = AdaBoostClassifier(n_estimators=1000)
clf = clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)
end_time = time.time()

print("Confusion matrix (Adaboost):")
print(confusion_matrix(pd.DataFrame(y_test), pd.DataFrame(y_pred.round())))
print("Total time(Adaboost):")
print(round((end_time - start_time), 4), "seconds")

Confusion matrix (Adaboost):
[[122  22   1   0   0   6 197]
 [171 127  10   0   0  62 115]
 [  0   5  11   0   0  50   0]
 [  0   0   0   0   0   5   0]
 [  1   8   0   0   0   4   0]
 [  0   2   7   0   0  29   0]
 [  9   0   0   0   0   0  36]]
Total time(Adaboost):
1084.5722 seconds


# The best Choice:

## As seen in the table, and as explained in my written section, the best method to make an accurate and not too timely prediction for the forest cover data is RandomForest in parallel

In [ ]:
name_accuracy_time = {'OG notes': [0.698, 3.7855], 'PCA': [0.834, 20.2837], 'RF reg': [0.953, 822.8674], 'RF parallel': [0.943, 619.7996], 'AdaBoost10': [0.558, 11.3], 'AdaBoost100': [0.329, 111.5685], 'AdaBoost1000': [0.325, 1084.5]}
n_a_t_matrix = pd.DataFrame.from_dict(name_accuracy_time, orient='index', columns=['Accuracy', 'Time'])
print(n_a_t_matrix)

              Accuracy       Time
OG notes         0.698     3.7855
PCA              0.834    20.2837
RF reg           0.953   822.8674
RF parallel      0.943   619.7996
AdaBoost10       0.558    11.3000
AdaBoost100      0.329   111.5685
AdaBoost1000     0.325  1084.5000
